# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laura Damaceno de Almeida
email: lauradamaceno60107@gmail.com
description: #>-  this means to ignore newlines until "baseurl:"
  Futura cientista da Computação, Pylady no Pyladies São Paulo, cofundadora do AI Girls e organizadora da comunidade DevAI Women.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lauradamacenoalmeida.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lauradamacenoalmeida
linkedin_username: laura-damaceno
instagram_username: laura_damaceno_almeida
author: Laura Damaceno de Almeida
background: "/img/bg-home-2.jpeg"

google_analytics: 'UA-163090919-1'

# Build settings
#theme: jekyll-theme-clean-blog
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - bootstrap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
